### ISSUE TITLE
Can't build using local zip file

### ISSUE THREAD

**Issue by shinglyu** [mozilla-b2g/preload-app-toolkit#72]
## Steps
- Create a packaged app locally
- Zip the app into `application.zip`
- Run `python preload.py /path/to/application.zip`
## Expected

The App is successfully built for preload
## Actual

Failed to fetch the local icon

```
Traceback (most recent call last):
  File "preload.py", line 323, in <module>
    main()
  File "preload.py", line 308, in main
    fetch_webapp(sys.argv[1])
  File "preload.py", line 264, in fetch_webapp
    key, manifest['icons'], domain, path, app_dir)
  File "preload.py", line 108, in fetch_icon
    icon_base64 = fetch_icon_from_url(iconurl)
  File "preload.py", line 84, in fetch_icon_from_url
    image = open_from_url(url).read()
  File "preload.py", line 45, in open_from_url
    return urllib.urlopen(url)
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 463, in open_file
    return self.open_local_file(url)
  File "/usr/lib/python2.7/urllib.py", line 477, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: ':///img/icons/icon48x48.png'
```

**Comment by gasolin** [comment]
This tool is intent to preload app from marketplace, not for local though.
So it only deal with a path list from internet

**Comment by shinglyu** [comment]
I see. Thank you.
